export enum CategoriesEnum {
  ACAO = 'Ação',
  AVENTURA = 'Aventura',
  MOBA = 'MOBA',
  RPG = 'RPG',
  MULTIPLAYER = 'Multiplayer',
  SINGLEPLAYER = 'Singleplayer',
  MUNDO_ABERTO = 'Mundo aberto',
  PRIMEIRA_PESSOA = 'Primeira pessoa',
  TERROR = 'Terror',
  HACK_AND_SLASH = 'Hack and slash',
  SOULS_LIKE = 'Souls like',
  CORRIDA = 'Corrida',
  ROMANCE_VISUAL = 'Romance visual',
  LUTA = 'Luta',
  ESPORTES = 'Esportes',
  ESTRATÉGIA = 'Estratégia',
  SOBREVIVENCIA = 'Sobrevivência',
  QUEBRA_CABECA = 'Quebra cabeça',
  ANIME = 'Anime',
  RETRO = 'Retrô',
  FPS = 'FPS',
  BATTLE_ROYALE = 'Battle Royale',
  METROIDVANIA = 'Metroidvania',
}
